#!/bin/bash

clear
cd ~/Desktop
read -p "Welcome to daveboot
What is the shortname for the user you would like to target? " SHORTNAME
clear
curl -O "http://davegrohl.org/DaveGrohl-2.1.zip" > /dev/null 2>&1 
unzip  Dave* > /dev/null 2>&1 
rm Dave*.zip
rm -r  __MACOSX
clear
cd Dave*
echo "daveboot needs sudo privileges:"
sudo ./Dave -u "$SHORTNAME"