#!/bin/bash

clear
mkdir /tmp/daveboot
cd /tmp/daveboot
read -p "Welcome to daveboot
What is the shortname for the user you would like to target? " SHORTNAME
clear
curl -sO "http://davegrohl.org/DaveGrohl-2.1.zip"
unzip Dave* > /dev/null 2>&1 
rm Dave*.zip
rm -r  __MACOSX
clear
cd Dave*
echo "daveboot may need sudo privileges: 
"
sudo ./dave -u "$SHORTNAME"
